#!/usr/bin/env bash
# Transfers a file from the client machine to the server

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
file="$1"
ip="$2"
username="$3"
keypath="$4"

scp -i $keypath -o StrictHostKeyChecking=no $file $username@$ip:/home/ubuntu/$file
