#!/usr/bin/env bash
# Copies a file using scp
if [ 3 -gt $# ];
then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
	exit
fi
file_to_copy="$1"
host="$2"
user="$3"
key="$4"

scp -i "$key" "$file_to_copy" "$user"@"$host":~/
