#!/usr/bin/env bash
# Creates a redirect_me directory and configures nginx server
apt-get update > /dev/null
apt-get -y install nginx > /dev/null
service nginx start
cfg="/etc/nginx/sites-enabled/default"
grep -q "/redirect_me" "$cfg" || sed -i "s|^\s*location\s*\/\s*{|\tlocation / {\n\n\t\tlocation /redirect_me {\n\t\t\treturn 301 https://linkedin/in/shaker-sharabi/;\n\t\t}\n|" "$cfg";
nginx -s reload
