#!/usr/bin/env bash
# Creates a redirect_me directory and configures nginx server
apt update
apt -y install nginx
sed -i "s|^\s*location\s*\/\s*{|\tlocation / {\n\n\t\tlocation /redirect_me/ {\n\t\t\treturn 301 https://linkedin/in/shaker-sharabi/;\n\t\t}\n|" /etc/nginx/sites-enabled/default;
service nginx reload

