#!/usr/bin/env bash
# Configures custom 404 page
apt-get update > /dev/null
apt-get install nginx > /dev/null
service nginx start
cfg="/etc/nginx/sites-enabled/default"
grep -q "/redirect_me/" "$cfg" || sed -i "s|^\s*location\s*\/\s*{|\tlocation / {\n\n\t\tlocation /redirect_me/ {\n\t\t\treturn 301 https://linkedin/in/shaker-sharabi/;\n\t\t}\n|" "$cfg";
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
grep -q "error_page 404" "$cfg" || sed -i "s/^server {/server {\n\terror_page 404 \/custom_404.html;/g" "$cfg"
nginx -s reload
