#!/usr/bin/env bash
# Script to print "To infinity and beyond" and handles signals

pidfile="/var/run/myscript.pid"
echo $$ > $pidfile
while true
do
	trap "echo 'I hate the kill command'; rm '/var/run/myscript.pid'; exit" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm '/var/run/myscript.pid'; exit" SIGQUIT
	echo "To infinity and beyond"
done
