#!/usr/bin/env bash
# Script to display numbers from 1 to 100 and diplays FizzBuzz if
# the number multiple of 3 and 5, Fizz if the number is multiple of 3,
# Buzz if the number is multple of 5 and the number otherwise

for n in {1..100}
do
	if [ "$(( n % 3))" -eq 0 ] && [ "$(( n % 5))" -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ "$(( n % 3))" -eq 0 ]
	then
		echo "Fizz"
	elif [ "$(( n % 5))" -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$n"
	fi
done
