#!/usr/bin/env bash
# Script to display the content of the "/etc/passwd" file

file="/etc/passwd"

if [ -e "$file" ]
then
	while read -r line
	do
		echo "$line" | cut -d : -f 1,3,6
	done < "$file"
fi
