#!/usr/bin/env bash
# Script to display "bad luck" in the 4th iteration, "good luck" in
# the 8th iteration and "Best School" in the other iterations

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done	
