#!/usr/bin/env bash
# Script to display numbers from 1 to 20 and display
# "bad luck from China" in the 4th iteration,
# "good luck from Jaban" in the 9th iteration and
# "bad luck from Italy" in the 17th itaration

n=1
while [ $n -le 20 ]
do
	echo "$n"
	case "$n" in
		"4" ) echo "bad luck from China";;
		"9" ) echo "bad luck from Japan";;
		"17" ) echo "bad luck from Italy";;
	esac
	((n++))
done
