#!/usr/bin/env bash
# Script to change the hosts file

sed -i "s/127.*.*.*   localhost/127.0.0.2   localhost/" /etc/hosts

if grep -Fxq "facebook.com" /etc/hosts
then
sed -i "s/*.*.*.*   facebook.com/8.8.8.8   facebook.com/" /etc/hosts
else
sed -i '1s/^/8.8.8.8   facebook\n/' /etc/hosts
fi
